import { Stack, Duration, CustomResource, RemovalPolicy } from 'aws-cdk-lib'
import { Role, ServicePrincipal, ManagedPolicy, PolicyDocument, PolicyStatement, IRole } from 'aws-cdk-lib/aws-iam'
import { Runtime } from 'aws-cdk-lib/aws-lambda'
import { NodejsFunction, SourceMapMode } from 'aws-cdk-lib/aws-lambda-nodejs'
import { RetentionDays } from 'aws-cdk-lib/aws-logs'
import { Provider } from 'aws-cdk-lib/custom-resources'
import { Construct } from 'constructs'
import { join } from 'path'

export type PlatformTypes = 'APNS' | 'APNS_SANDBOX'

export type AbstractSNSPlatformApplicationOptions = {
    name: string,
    platform: PlatformTypes,
    attributes?: { [key: string]: string }
}

export abstract class AbstractSNSPlatformApplication extends Construct {

    protected name: string
    protected platform: PlatformTypes
    protected attributes?: { [key: string]: string }

    protected provider: Provider
    protected resource: CustomResource
    protected role: IRole
    protected onEventHandler: NodejsFunction

    
    constructor(scope: Construct, id: string, options: AbstractSNSPlatformApplicationOptions ){
        super(scope, id)

        this.name = options.name
        this.platform = options.platform
        this.attributes = options.attributes

        this.role = this.setupRole()
        this.afterRoleCreation()
        this.onEventHandler = this.setupEventHandler(this.role)

        this.provider = new Provider(this, 'Provider', {
            onEventHandler: this.onEventHandler,
            logRetention: RetentionDays.ONE_DAY
        })

        this.resource = new CustomResource(this, 'Resource', {
             serviceToken: this.provider.serviceToken,
             properties: this.buildEventHandlerProperties(),
             removalPolicy: RemovalPolicy.DESTROY,
             resourceType: this.resourceType()
        })
    }

    abstract resourceType(): string

    abstract buildEventHandlerProperties(): { [key: string]: string }

    afterRoleCreation(){
        // no-op
    }

    protected setupRole(): Role {
        return new Role(this, `Role`, {
            assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
            managedPolicies: [
                ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')
            ],
            inlinePolicies: {
                'ManageSNSPlatformApplications': new PolicyDocument({
                    statements: [
                        new PolicyStatement({
                            actions: [
                                'sns:CreatePlatformApplication',
                                'sns:DeletePlatformApplication',
                                'sns:ListPlatformApplications',
                                'sns:SetPlatformApplicationAttributes'
                            ],
                            resources: [
                                `arn:aws:sns:${Stack.of(this).region}:${Stack.of(this).account}:app/*`
                            ]
                        })
                    ]
                })
            },
            description: `Used to execute the @general-galactic/cdk-resources -> ${this.node.id} event handler lamda`
        })
    }

    protected setupEventHandler(role: IRole): NodejsFunction {
        return new NodejsFunction(this, 'EventHandler', {
            runtime: Runtime.NODEJS_14_X,
            memorySize: 1024,
            timeout: Duration.minutes(5),
            entry: join(__dirname, `../../../resources/lambdas/SNSPlatformApplicationCustomResourceHandler/index.js`),
            handler: 'main',
            bundling: {
              externalModules: ['aws-sdk'],
              sourceMap: true,
              sourceMapMode: SourceMapMode.INLINE,
              target: 'es2020',
              banner: '/* WARNING: THIS FILE WAS GENERATED BY THE CDK - DO NOT EDIT! */'
            },
            role,
            environment: {
              NODE_OPTIONS: '--enable-source-maps'
            },
            logRetention: RetentionDays.THREE_DAYS,
            description: 'Used to manage SNS Platform Application updates from CloudFormation / CDK -- created by @general-galactic/cdk-resources'
        })
    }

    get PlatformApplicationArn(): string | undefined {
        return this.resource?.getAttString('PlatformApplicationArn')
    }

}