import { CustomResource, Duration, RemovalPolicy, Stack } from 'aws-cdk-lib'
import { PolicyDocument, PolicyStatement } from 'aws-cdk-lib/aws-iam'
import { Runtime } from 'aws-cdk-lib/aws-lambda'
import { NodejsFunction, SourceMapMode } from 'aws-cdk-lib/aws-lambda-nodejs'
import { RetentionDays } from 'aws-cdk-lib/aws-logs'
import { Construct } from 'constructs'
import { join } from 'path'
import { Provider } from 'aws-cdk-lib/custom-resources'


/**
 * This is a custom CDK resource to be used in place of IotPolicy. IotPolicy doesn't support
 * policy versions and will just replace the policy or error: (https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/469).
 * 
 * This custom resource allows creating a policy from scratch, incrementing policy version on updates, deleting old policy versions
 * once there are more than 5, and deleting the policy versions when tearing down a stack.
 * 
 */
export class IoTCorePolicy extends Construct {

    readonly policyName: string
    readonly provider: Provider
    readonly resource: CustomResource

    constructor(scope: Construct, policyName: string, policyDocument: PolicyDocument) {
        super(scope, 'IoTCorePolicy')

        this.policyName = policyName

        const onEventHandler = this.setupEventHandler()

        if(onEventHandler.role){
            onEventHandler.role.addToPrincipalPolicy(new PolicyStatement({
                actions: [
                    'iot:GetPolicy',
                    'iot:CreatePolicy', 
                    'iot:DeletePolicy',
                    'iot:ListPolicyVersions', 
                    'iot:CreatePolicyVersion', 
                    'iot:DeletePolicyVersion'
                ],
                resources: [
                    `arn:aws:iot:${Stack.of(this).region}:${Stack.of(this).account}:policy/${policyName}`
                ]
            }))
        }

        this.provider = new Provider(this, 'Provider', {
            onEventHandler,
            logRetention: RetentionDays.ONE_DAY
        })

        this.resource = new CustomResource(this, 'Resource', {
            serviceToken: this.provider.serviceToken,
            properties: {
                policyName,
                policyDocument: JSON.stringify(policyDocument.toJSON()),
                region: Stack.of(this).region,
                account: Stack.of(this).account
            },
            removalPolicy: RemovalPolicy.DESTROY,
            resourceType: 'Custom::GG-IoTCorePolicy'
        })
    }

    private setupEventHandler(): NodejsFunction {
        return new NodejsFunction(this, `IOTCorePolicyVersionEventHandler`, {
            runtime: Runtime.NODEJS_14_X,
            memorySize: 1024,
            timeout: Duration.minutes(5),
            entry: join(__dirname, `../../../resources/lambdas/IoTCorePolicyVersionEventHandler/index.js`),
            handler: 'main',
            bundling: {
              externalModules: ['aws-lambda'],
              sourceMap: true,
              sourceMapMode: SourceMapMode.INLINE,
              target: 'es2020',
              banner: '/* WARNING: THIS FILE WAS GENERATED BY THE CDK - DO NOT EDIT! */'
            },
            environment: {
              NODE_OPTIONS: '--enable-source-maps'
            },
            logRetention: RetentionDays.THREE_DAYS,
            description: 'Used to manage IoT Core Policy updates from CloudFormation / CDK -- created by @general-galactic/cdk-resources'
        })
    }

    get deletedPolicyVersion(): string | undefined {
        return this.resource?.getAttString('deletedVersion')
    }

    get createdPolicyVersion(): string | undefined {
        return this.resource?.getAttString('createdVersion')
    }

    get policyArn(): string | undefined {
        return this.resource?.getAttString('policyArn')
    }

}