import { CustomResource, Duration, RemovalPolicy, Stack } from 'aws-cdk-lib'
import { ManagedPolicy, PolicyDocument, PolicyStatement, Role, ServicePrincipal } from 'aws-cdk-lib/aws-iam'
import { Runtime } from 'aws-cdk-lib/aws-lambda'
import { NodejsFunction, SourceMapMode } from 'aws-cdk-lib/aws-lambda-nodejs'
import { RetentionDays } from 'aws-cdk-lib/aws-logs'
import { Construct } from 'constructs'
import { join } from 'path'
import { Provider } from 'aws-cdk-lib/custom-resources'


type PlatformTypes = 'ADM' | 'APNS' | 'APNS_SANDBOX' | 'GCM'

export type SNSPlatformApplicationOptions = {
    name: string
    platform: PlatformTypes
    attributes?: { [key: string]: string }
}

export class SNSPlatformApplication extends Construct {

    readonly name: string
    readonly platform: PlatformTypes
    readonly attributes?: { [key: string]: string }
    readonly provider: Provider
    readonly resource: CustomResource

    constructor(scope: Construct, name: string, platform: PlatformTypes, attributes?: { [key: string]: string }) {
        super(scope, 'SNSPlatformApplication')

        this.name = name
        this.platform = platform
        this.attributes = attributes

        const role = this.setupRole()

        const onEventHandler = this.setupEventHandler(role)

        this.provider = new Provider(this, 'Provider', {
            onEventHandler,
            logRetention: RetentionDays.ONE_DAY
        })

        this.resource = new CustomResource(this, 'Resource', {
            serviceToken: this.provider.serviceToken,
            properties: {
                name: this.name,
                platform: this.platform,
                attributes: this.attributes,
                region: Stack.of(this).region,
                account: Stack.of(this).account
            },
            removalPolicy: RemovalPolicy.DESTROY,
            resourceType: 'Custom::GG-SNSPlatformApplication'
        })
    }

    private setupRole(): Role {
        return new Role(this, `Role`, {
            assumedBy: new ServicePrincipal('sns.amazonaws.com'),
            managedPolicies: [
                ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')
            ],
            inlinePolicies: {
                'ManageSNSPlatformApplications': new PolicyDocument({
                    statements: [
                        new PolicyStatement({
                            actions: [
                                'sns:CreatePlatformApplication',
                                'sns:DeletePlatformApplication',
                                'sns:ListPlatformApplications',
                                'sns:SetPlatformApplicationAttributes'
                            ],
                            resources: [
                                `arn:aws:sns:${Stack.of(this).region}:${Stack.of(this).account}:app/*`
                            ]
                        })
                    ]
                })
            },
            description: 'Used to execute the @general-galactic/cdk-resources -> SNSPlatformApplicationCustomResourceEventHandler lamda'
        })
    }

    private setupEventHandler(role: Role): NodejsFunction {
        return new NodejsFunction(this, `ManageSNSPlatformApplicationCustomResourceEventHandler`, {
            runtime: Runtime.NODEJS_14_X,
            memorySize: 1024,
            timeout: Duration.minutes(5),
            entry: join(__dirname, `../../../resources/lambdas/SNSPlatformApplicationCustomResourceHandler/index.js`),
            handler: 'main',
            bundling: {
              externalModules: ['aws-sdk'],
              sourceMap: true,
              sourceMapMode: SourceMapMode.INLINE,
              target: 'es2020',
              banner: '/* WARNING: THIS FILE WAS GENERATED BY THE CDK - DO NOT EDIT! */'
            },
            role,
            environment: {
              NODE_OPTIONS: '--enable-source-maps'
            },
            logRetention: RetentionDays.THREE_DAYS,
            description: 'Used to manage SNS Platform Application updates from CloudFormation / CDK -- created by @general-galactic/cdk-resources'
        })
    }

}